apiVersion: v1
kind: Service
metadata:
  name: happymates-blob
  namespace: happymates-blob
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: happymates-blob
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
